### PR TITLE
Assignment 3

### PR DESCRIPTION
**Pull request by VictorNS69**
This will also close #230  (my assignment 4)

### CODE REVIEW

**Comment by dmorgera** [comment]
Tu aproximación al problema me ha parecido muy interesante! Seguiré de cerca tu progreso

**Comment by VictorNS69** [comment]
> Tu aproximación al problema me ha parecido muy interesante! Seguiré de cerca tu progreso

Gracias compañero, nos veremos en clase aprendiendo un montón!

Saludos!

**Comment by ocorcho** [comment]
Sorry, I made a mistake deleting two files. They were right. I will add them in the master repository again.

**Comment by ocorcho** [comment]
@dachafra I accepted this pull request and did not realise that there were files for assignment 4. Please review them.

**Comment by dachafra** [comment]
the files are already in the github repo, he has submitted other pull request

**Pull request merged**
