### PR TITLE
assigment2 handson v1

### PR DESCRIPTION
**Pull request by GuilleSB97**

### CODE REVIEW

**Comment by GuilleSB97** [comment]
HandsOn 2 vfinal

**Comment by rgcmme** [comment]
- The resource naming strategy is not defined.
- You are removing the self-assessment template. Remove this change from the pull request.
- The ontology is giving me problems when I try to open it in Protege.
- Check that all property names start with non-capital letter.
- A postal code is not an integer, it is a string. The same happens with Puerta.
- There is no range for email.
- It is better to avoid using subproperties. Just define the children properties.

**Comment by GuilleSB97** [comment]
Please can you check if everything is correct to proceed to the next delivery?
Thank you
@rgcmme

**Comment by rgcmme** [comment]
OK

**Pull request merged**
