### PR TITLE
Upload Assignment 3

### PR DESCRIPTION
**Pull request by AndreaVentur10**

### CODE REVIEW

**Comment by ocorcho** [comment]
Assignment 3 ok. Now @dachafra can check assignment 4

**Comment by dachafra** [comment]
please, add task 7 (it is also mandatory)

**Comment by dachafra** [comment]
if the file of task 7 is not added before Friday 25th I will close de PR

**Comment by ocorcho** [comment]
PR closed, as discussed by @dachafra

**Pull request closed without merging**
