### PR TITLE
belengonlaf Assignment4 and HandsOn1

### PR DESCRIPTION
**Pull request by belengonlaf**

### CODE REVIEW

**Comment by rgcmme** [comment]
- You are including two files for the assignment 4 that have no student name. Remove them from the pull request.
- There is no analysis on how the data can be linked.
- The self-assessment file is not filled.

**Comment by dachafra** [comment]
please add Task 06 and 07 from Assign 4 in a folder, not with your name in the file

**Comment by dachafra** [comment]
still incorrect, you have to create a folder with your name inside the assign4 folder. It is explained in the README of the root folder

**Comment by dachafra** [comment]
assign4 ok, now time for @rgcmme

**Pull request merged**
